image: Ubuntu
cache:
  - node_modules
install:
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - sudo apt install nodejs -y
  - set CI=true
  - npm install -g npm@latest
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run build
