image: Ubuntu
cache:
  - node_modules
environment:
  matrix:
  - nodejs_version: "14"
install:
  - sudo apt-get purge -qq --auto-remove nodejs
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - sudo apt-get install -qq -y nodejs
  - node -v 
  - set CI=true
  - npm install -g npm@latest
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run build
